print("PART 8: File Handling")

file=open("TextFile.txt", "w")
file.write("I am doing internship at SAMStack Tech.\n")
file.write("I learned python specialization.\n")
file.close()
file=open("TextFile.txt", "r")
print(file.read())
file.close()
file=open("TextFile.txt", "a")
file.write("This is an additional line.\n")
file.close()
file=open("TextFile.txt", "r")
print(file.read())
file.close()